name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Build (PyInstaller)
        run: |
          pyinstaller --noconfirm --onefile \
            --windowed \
            --icon zapret.ico \
            --hidden-import=win32com \
            --hidden-import=win32com.client \
            --hidden-import=pythoncom \
            --name zapret main.py

          # Переименовываем для Windows-пользователей
          mv dist/zapret dist/zapret.exe

          echo "== dist после переименования =="
          ls -l dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zapret-exe
          path: dist/zapret.exe
