# .github/workflows/windows-build.yml
name: Windows build (PyInstaller)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-win:
    runs-on: windows-latest          # ⇒ GitHub выдаёт Win Server 2022
    env:                             # переменные видны и в .bat
      PYTHONUTF8: "1"                # чтобы избежать проблем с кодировкой
      CI: "true"                     # помечаем, что это CI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"     # выберите нужную версию

      # ♦♦♦  Все зависимости, которые нужны build.bat  ♦♦♦
      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pywin32
          if exist requirements.txt pip install -r requirements.txt

      # ♦♦♦  Запуск .bat  ♦♦♦
      - name: Run build.bat
        shell: cmd                   # важно! иначе по умолчанию PowerShell
        run: |
          call build.bat --ci

      # ♦♦♦  Сохраняем результат (exe-файл) как артефакт  ♦♦♦
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zapret-exe
          path: zapret/zapret.exe
