name: Build & publish Windows binary

on:
  release:
    types: [created]

permissions:
  contents: write    # чтобы загружать asset

jobs:
  build-win:
    runs-on: windows-2022   # ← гарантированно Windows Server 2022
    env:
      CI: "true"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"      # можно "x86", если нужны 32-битные EXE

      - name: Install PyInstaller & deps
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pywin32

      - name: Build EXE (build.bat)
        shell: cmd
        run: |
          call build.bat --ci

      - name: Upload zapret.exe to release
        uses: softprops/action-gh-release@v2
        with:
          files: zapret/zapret.exe     # путь до вашего EXE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
