# .github/workflows/windows-release.yml
name: Build & publish Windows binary

on:
  release:
    types: [created]

permissions:
  contents: write     # публикация assets к релизу

jobs:
  build-win:
    runs-on: windows-latest
    env:
      CI: "true"      # чтобы build.bat знал, что мы в CI

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ⬇⬇⬇  ВАЖНО: shell: cmd   ⬇⬇⬇
      - name: Install PyInstaller & deps
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pywin32

      - name: Build EXE (build.bat)
        shell: cmd
        run: |
          call build.bat --ci

      - name: Upload zapret.exe to release
        uses: softprops/action-gh-release@v2
        with:
          files: zapret/zapret.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
